_wandb:
    value:
        cli_version: 0.24.0
        e:
            116824gv9u4oa7j9sk60iqcty72xws0y:
                codePath: main.py
                codePathLocal: main.py
                cpu_count: 24
                cpu_count_logical: 48
                disk:
                    /:
                        total: "232950988800"
                        used: "728760320"
                email: lorantnagy28@gmail.com
                executable: /usr/local/bin/python
                git:
                    remote: git@github.com:lorant-nagy/sde-mixing.git
                host: cca9f92038e4
                memory:
                    total: "270321209344"
                os: Linux-5.15.0-91-generic-x86_64-with-glibc2.41
                program: /workspace/main.py
                python: CPython 3.11.14
                root: /workspace
                startedAt: "2026-01-23T14:13:49.737034Z"
                writerId: 116824gv9u4oa7j9sk60iqcty72xws0y
        m: []
        python_version: 3.11.14
        t:
            "3":
                - 2
                - 16
            "4": 3.11.14
            "5": 0.24.0
            "10":
                - 21
            "12": 0.24.0
            "13": linux-x86_64
M:
    value: 10000
M_stat:
    value: 50000
"N":
    value: 15000
R_values:
    value:
        - 2
        - 4
        - 8
        - 16
        - 32
        - 64
        - 128
        - 256
T_max:
    value: 15
drift_power:
    value: 3
eps_TV:
    value: 0.05
eps_W:
    value: 0.05
every_k:
    value: 10
mu:
    value: 1
p0_KS:
    value: 0.05
sigma:
    value: 1.4142135623730951
wandb_entity:
    value: null
wandb_project:
    value: ou-vs-superlinear
